### PR TITLE
Add styles for minimap component

### LINKED ISSUE #90: Add styles for minimap component
Use Story from issue #89.

### PR DESCRIPTION
**Pull request by HaSistrunk**
Fixes #90 

Updated notes:

I made some changes to the html: 
- Changed `minimap_hit` to `minimap__record-hit` because I created a `minimap_hit` mixin that both classes use
- Added a span in the links to insert the checkmark for visited links
- Added a div wrapper to the handlebars files in Storybook with inline styles.

I also learned that to style visited links, for security reasons, [browsers only allow a small number of properties](https://developer.mozilla.org/en-US/docs/Web/CSS/:visited#privacy_restrictions) to be used with the `::visited` psuedo class (basically color changes). So for the checkmark styles to be added to visited links, I've added the checkmark and just changed its color to be visible after the link is visited.

### CODE REVIEW

**Comment by helrond** [comment]
@HaSistrunk looking good!

There are things called [decorators](https://storybook.js.org/docs/react/writing-stories/decorators) in Storybook which would seem to be the thing to use to add a wrapping div. If that doesn't work, I'm not opposed to adding a wrapper in the handlebars file and adding inline styles.

>So for the checkmark styles to be added to visited links, I've added the checkmark and just change its color to be visible after the link is visited.

Does this ☝️ create an accessibility issue?

**Comment by HaSistrunk** [comment]
> > So for the checkmark styles to be added to visited links, I've added the checkmark and just change its color to be visible after the link is visited.
> 
> Does this ☝️ create an accessibility issue?

Ah, good question. I was thinking that screenreaders wouldn't read that content, but I checked and it turns out that some do and some don't. So the better solution may be to add the checkmarks to the html so we can include an `aria-hidden='true'` on it.

Screenreaders _will_ state if a link has been visited before reading the link text, so they take care of that for us.

**Comment by helrond** [comment]
OK cool, do you want to add the HTML here and I'll follow suit in DIMES?

**Comment by HaSistrunk** [comment]
Ok, see how that looks. 

I just learned about a WCAG criteria related to target size, with AA specifying a minimum area of 24px x 24px. But after I implemented that as a minimum size here, I realized that that [criteria is only in WCAG 2.2](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html), which is still in draft form. WCAG 2.1 doesn't have a Level AA guideline for target size. So it may not be very forward thinking, but we _could_ make them smaller (ondesign has them as 14px squares).

**Comment by helrond** [comment]
The minimap slaps you in the face a bit with this square size, but perhaps that's not a bad thing? I reduced the row size to 4 and gave the wrapper a fixed width and it looks like this:
Screen Shot 2021-10-06 at 5 23 48 PM

I _think_ because the hover action grows by a percentage, there are weird artifacts when the container doesn't have enough space to accommodate the increased width. This is unfortunate because it means that the squares actually have to be bigger than 24px. Wondering if there's anything that can be done about that?

A couple of other things I'm seeing:
- I added a `margin: 0` to `.minimap__box` in order to override a `margin-bottom` coming from `a`
- I think the `gap` on the `.minimap` grid should actually be 8px up through tablets, so that `@inclue md-up` should actually be `@include lg-up`.
- The currently active area is not styled differently than others. I think we may have to add a class in React and then style that?

**Comment by helrond** [comment]
Yeah that doesn't work because clicking on the link reloads the page, and `:active` styling only applies to links you click. https://developer.mozilla.org/en-US/docs/Web/CSS/:active

**Comment by HaSistrunk** [comment]
1. It does slap the face. I guess let's try it? Our general aesthetic tends to lean small. We could also consider using media queries for pointer device to adjust size based on "course" or "fine" input interactions, but would have to do more research on that.
2. I removed the hover action that grows the boxes. That isn't in the designs and I don't think is necessary with the larger size.
3. I added new classes for active areas (one for digital hits and one for records hits).

**Review by helrond — APPROVED** [review]
Let's get this merged to development now that we're actively testing!

**Pull request merged**
