### PR TITLE
Adds table component

### LINKED ISSUE #144: Add a table component
We don't yet have a design for table styles. Create design and add styles/component to library.

### PR DESCRIPTION
**Pull request by helrond**
Adds an HTML table component and associated styles.

Fixes #144

### CODE REVIEW

**Comment by HaSistrunk** [comment]
Two things:
1. Is there a reason why the column titles are centered and the values are left aligned? I feel like it makes it hard to align visually which values go with which heading.
2. What do you think about having two stories here? One that is a basic implementation with no inputs, and one that includes the inputs. I feel like for grabbing this HTML to add a simple table to a site, that will make it easier to copy over the code instead of pulling out all the unnecessary parts from the more complicated version.

**Comment by helrond** [comment]
Good call on both. I've left-aligned headers and cell content, and have added a second story specifically for the inputs scenario.

**Comment by HaSistrunk** [comment]
I'm seeing that scope isn't strictly necessary in the basic table implementation, but many argue it's a good idea for consistency and ease if a table starts out simple and gets complicated over time, so probably makes sense to leave it there as you have.

And are you thinking that it's good to provide id values in the basic table to build in the ability to add data programmatically?

**Comment by helrond** [comment]
I was, although now that I think about it it probably makes sense to pull those out until we have additional definition around the Javascript piece. I've removed those here.

**Review by HaSistrunk — APPROVED** [review]

**Pull request merged**
