### PR TITLE
Adds modal styles

### LINKED ISSUE #62: Add styles for basic modal component
- See dimes `_modal-base.scss` styles
- Note changes for BEM conformance

### PR DESCRIPTION
**Pull request by helrond**
Adds styles for modal component. 

Notes:
- For simplicity's sake I just have the modal open, rather than scaffolding up a fully interactive component which can be launched and closed. Would be interested in what folks think about that.
- The DIMES styles for modals include some utility classes to slide them in and out, which I have not included here, but I think might potentially make good mixins.

fixes #62

### CODE REVIEW

**Comment by bonniegee** [comment]
It's possible I'm doing something wrong, but I think because the modal is open, I'm unable to view the docs in Storybook (the model is blocking everything).

**Comment by helrond** [comment]
@bonniegee you're not doing anything wrong, I forgot to check how the docs were rendering. What do folks think about mocking out the open/close functionality of the modal? Given that it's absolutely positioned, that may be the only way to have this embedded in documentation.

This would require writing a small React component, which would not be hard. My concern is that future implementers might have a hard time figuring out what the need to do in order to make the modal work as expected. I suppose that could be mitigated with documentation though. Thoughts?

**Comment by HaSistrunk** [comment]
So am I understanding correctly that the options you're proposing are to:
1. Remove `<Story story={stories.basic} />` from the documentation and include documentation about what to do to make the modal function as expected.
OR
2. Mock up the open close function of the modal with a react component to demonstrate function.

**Comment by helrond** [comment]
I was thinking option 2, with some added documentation about how to implement the JS necessary to open/close the modal.

I don't think option 1 is a good one because there would be no preview of the modal, which seems like a nonstarter.

**Comment by HaSistrunk** [comment]
> I was thinking option 2, with some added documentation about how to implement the JS necessary to open/close the modal.
> I don't think option 1 is a good one because there would be no preview of the modal, which seems like a nonstarter.

Seems like the way to go if you're down to do it.

**Comment by HaSistrunk** [comment]
Nice!

**Review by HaSistrunk — APPROVED** [review]

**Review by p-galligan — APPROVED** [review]

**Review by bonniegee — APPROVED** [review]

**Pull request merged**
