### PR TITLE
Adds color variables

### LINKED ISSUE #1: Add color variables
- Evaluate using HSL v. RGB v. hexadecimal
- Research uses of built-in [sass:color module](https://sass-lang.com/documentation/modules/color) to build new colors based on existing ones, and look at simplifying existing color space (compare `lighten/ darken` v. `mix` (with black or white) v. `scale` as methods).

### PR DESCRIPTION
**Pull request by HaSistrunk**
Fixes #1 
Adds initial set of color variables and html swatches. 

- Contains 4 fewer colors than the dimes styles, but we may want to pare down further as we build out component styles and replace specific colors with Sass color functions. We'll also want to evaluate color in the context of component accessibility to minimize contrast issues.
- Uses hsl color values, and places color variables in order of hue to help think through future applications of Sass color functions to alter hue, saturation, and lightness.
- Uses SassDoc notation, which we can change once if we decide to use a different documentation approach to support a style library.

Useful tools for future work with color (adding to internal resources doc):
1. Hex/hsl converter: https://colordesigner.io/convert/hextohsl
2. Sass color function calculator: http://razorltd.github.io/sasscolourfunctioncalculator/
3. Visualize Sass hsl color functions: [https://sassme.jim-nielsen.com/](https://sassme.jim-nielsen.com/)
4. Color palette accessibility checker: [https://oomphinc.github.io/colorcube/](https://oomphinc.github.io/colorcube/)

### CODE REVIEW

**Review by helrond — APPROVED** [review]
Cool, I'm inclined to get this merged and iterate. A couple things occur to me though, which could maybe be added as TODOs?
- Review color variable names. The `light-orange` color is pretty obviously pink, and we may want to use a standardized naming approach for naming other colors.
- Having the HSL values is super useful because there are a couple places where we can maybe simplify by moving to a single hue (like the blues) and from there doing some consistent math to get variations (like with the grays).

Otherwise, I think having an separate style guide with its own stylesheet is _already_ somewhat ungainly, so I think we'll want to move away from that ASAP.

**Comment by HaSistrunk** [comment]
Ok great, I've updated the color names to use the hue and closest named color (roughly), and updated the TODO to more specifically note that we'll want to it narrow things to a single a hue and calculate variations from those. I'll merge if the color names look ok.

**Comment by helrond** [comment]
Yup, this looks good! I think we'll want to eventually add more generalized variables like `brand-primary` and `brand-secondary` for colors, but I'm guessing that should live in `themes`?

**Comment by HaSistrunk** [comment]
> Yup, this looks good! I think we'll want to eventually add more generalized variables like `brand-primary` and `brand-secondary` for colors, but I'm guessing that should live in `themes`?

Yeah I think so. From the documentation for this [7-1 architecture](https://sass-guidelin.es/#the-7-1-pattern), I think we can put those in `/themes` if we anticipate or want to make space for multiple themes, but we can also not use that at all and keep everything in variables (or add a separate file for color variables if that gets unwieldy).

**Pull request merged**
